### ISSUE TITLE
Add `beforeSendTransaction`

### ISSUE THREAD

**Issue by vladanpaunovic** [getsentry/team-webplatform-meta#1]
Problem Statement
Similar to beforeSend, we will add beforeSendTransaction to allow people to strip Pii or drop transactions before they are sent to Sentry.

- [x] Python https://github.com/getsentry/sentry-python/issues/1738
- [x] Ruby https://github.com/getsentry/sentry-ruby/issues/1937
- [x] PHP https://github.com/getsentry/sentry-php/pull/1424
- [x] Javascript https://github.com/getsentry/sentry-javascript/pull/6121
- [x] Java https://github.com/getsentry/sentry-java/issues/2358
- [x] Go https://github.com/getsentry/sentry-go/issues/500
- [x] .NET https://github.com/getsentry/sentry-dotnet/issues/2077

**Comment by mattjohnsonpint** [comment]
See also: https://github.com/getsentry/team-mobile/issues/72
