### ISSUE TITLE
SDK Usage Context

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-webplatform-meta#11]
### Problem Statement

Events sent to Sentry are agnostic of how the applications loaded the SDK. Meaning npm download and install, CDN, or lazy loading. In some context when debugging problems it might be valuable to know how and when the SDK was loaded in the applications.

The description: The installation mechanism for the SDK. This can be a package manager like `npm` or `pip` or a custom installation mechanism like `agent` or `CDN`.

### Solution Brainstorm

- [ ] Add new field to [SDK interface](https://develop.sentry.dev/sdk/event-payloads/sdk/): `source` (name tbd) and get approval from all SDK teams
- [ ] Update SDK interface in Relay
- [ ] Create data ticket to query this data via looker
- [ ] Update JS SDK to add field
