### ISSUE TITLE
Introduce `includeLocalVariables` option

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/team-webplatform-meta#12]
Currently the PHP, Python, Ruby and NodeJS SDKs support local variables, but they all use inconsistent names for the option that gates this functionality.

- Ruby: [`capture_exception_frame_locals`](https://docs.sentry.io/platforms/ruby/configuration/options)
- Python: [`with_locals`](https://docs.sentry.io/platforms/python/configuration/options/#with-locals)
- PHP no option
- NodeJS [`_experiments.includeStackLocals`](https://docs.sentry.io/platforms/node/configuration/options/#_experiments.include-stack-locals)

This task tracks introducing a `includeLocalVariables` option that unifies this option.

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/develop/pull/813
- [ ] https://github.com/getsentry/sentry-python/issues/1854
- [x] https://github.com/getsentry/sentry-ruby/issues/1986
- [x] ~~https://github.com/getsentry/sentry-php/issues/1448~~
- [x] https://github.com/getsentry/sentry-javascript/issues/6873
- [x] https://github.com/getsentry/sentry-docs/issues/6124
```
