### ISSUE TITLE
Sanitize URLs in Span description and breadcrumbs

### ISSUE THREAD

**Issue by antonpirker** [getsentry/team-webplatform-meta#2]
HTTP Client Integrations record the URLs of HTTP requests. URLs can contain sensitive information like credentials or PII. This data should be removed before sending the events to Sentry.

See this PR in develop docs:
https://github.com/getsentry/develop/pull/773

- [x] Go: not applicable, no instrumentation for http clients in Go
- [x] Java: https://github.com/getsentry/sentry-java/issues/2365
- [x] PHP: https://github.com/getsentry/sentry-php/issues/1429
- [x] Python: https://github.com/getsentry/sentry-python/issues/1742
- [x] Node: https://github.com/getsentry/sentry-javascript/issues/6389
- [x] Browser JS: https://github.com/getsentry/sentry-javascript/pull/15404
- [x] Ruby: https://github.com/getsentry/sentry-ruby/issues/1955
- [x] .NET: https://github.com/getsentry/sentry-dotnet/issues/2078
 
Other Platforms:
- [x] Mobile meta issue: https://github.com/getsentry/team-mobile/issues/70
- [ ] Rust: https://github.com/getsentry/sentry-rust/issues/516

**Comment by vladanpaunovic** [comment]
@antonpirker can you put here a list of all affected SDKs that are problematic today?

**Comment by marandaneto** [comment]
Mobile [meta issue](https://github.com/getsentry/team-mobile/issues/70)

**Comment by smeubank** [comment]
@jjbayer is ingest aware of this work? Are there changes planned for relay to consider this work and make it relevant?

**Comment by jjbayer** [comment]
> @jjbayer is ingest aware of this work? Are there changes planned for relay to consider this work and make it relevant?

@smeubank there is no work planned. The linked Relay issue is not specifically about URLs. Are Relay changes even necessary, or is it considered more of an added bonus? Probably best to contact Jernej if there is a bigger Relay story we want to get into the upcoming quarter.

**Comment by mattjohnsonpint** [comment]
Rendered spec: https://develop.sentry.dev/sdk/data-handling/
