### ISSUE TITLE
Tracking OTEL Usage

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/team-webplatform-meta#3]
This is done through the existence of `event.contexts.otel` as per: https://develop.sentry.dev/sdk/performance/opentelemetry/

- [x] Data team Jira ticket: https://getsentry.atlassian.net/browse/DATA-1275
- [x] OTEL Analytics in Relay https://github.com/getsentry/relay/issues/1615
- [x] OTEL Analytics in Sentry frontend and backend https://github.com/getsentry/sentry/issues/41652

**Comment by AbhiPrasad** [comment]
Amplitude: https://analytics.amplitude.com/sentry/chart/zmqk4u1

DataDog: https://app.datadoghq.com/notebook/4004954/opentelemetry-usage

Sentry: https://sentry.io/organizations/sentry/dashboard/29945/?project=11276&statsPeriod=7d
