### ISSUE TITLE
Pickup and forward `replay_id` from DSC

### ISSUE THREAD

**Issue by HazAT** [getsentry/team-webplatform-meta#41]
We want to add `replay_id` to the DSC and all SDKs should pick it up and forward it to Relay:

```[tasklist]
### Tasks
- [x] Javascript: https://github.com/getsentry/sentry-javascript/issues/7555
- [x] Java
- [x] .NET
- [x] Python: https://github.com/getsentry/sentry-python/pull/1970
- [x] Ruby: https://github.com/getsentry/sentry-ruby/pull/2025
- [x] PHP
- [x] Go
- [x] Node
```

**Comment by JoshFerge** [comment]
quick notes: only js needs to add replay_id to the DSC, the relevant backend SDKs need to forward the DSC along with errors if performance is enabled.

**Comment by HazAT** [comment]
Yes, @JoshFerge - thank you for clarifying that.
We'll check all backend SDKs that this is working (PHP & Go) already do it

**Comment by mattjohnsonpint** [comment]
.NET already forwards all `sentry-` headers.

**Comment by JoshFerge** [comment]
Perhaps something was lost in the ether here:

From my comment above
> the relevant backend SDKs need to forward the DSC **along with errors** if performance is enabled.

I just tried propagating the replay_id on the node.js express backend, and we are _not_ forwarding the DSC along with error events. 

It appears we only add the DSC to envelopes if the event.type is transaction
https://github.com/getsentry/sentry-javascript/blob/88d94aff7cbe3cca07de76b4b8df7f971674be23/packages/utils/src/envelope.ts#L245

re-opening.

(on a sidenote, i can confirm i'm seeing replay_ids along with backend transactions. nice!)

**Comment by AbhiPrasad** [comment]
Next release makes this work on Node: https://github.com/getsentry/sentry-javascript/issues/7819

**Comment by HazAT** [comment]
Also Python
https://github.com/getsentry/sentry-python/pull/2009
