### ISSUE TITLE
Project: ignoreErrors & ignoreTransactions Options

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-webplatform-meta#46]
https://github.com/getsentry/develop/pull/884

Develop docs updated: https://develop.sentry.dev/sdk/features/#event-sampling

https://www.notion.so/sentry/RFC-for-ignoreTransactions-5ba68f17867e4bb08e80f1ec7f9805dd

- [x] getsentry/sentry-python#2018
- [x] javascript - https://github.com/getsentry/sentry-docs/pull/6642
- [x] getsentry/sentry-docs#6648
- [x] getsentry/sentry-docs#6666
- [x] getsentry/sentry-go#628
- [x] getsentry/sentry-java#2660
- [x] https://github.com/getsentry/team-mobile/issues/108
- [ ] https://github.com/getsentry/sentry-dotnet/issues/2306

**Comment by sl0thentr0py** [comment]
in ruby, `ignore_errors` is called `excluded_exceptions` (we can deprecate and rename if necessary, but I think it's fine).
`ignore_transactions` doesn't exist.

**Comment by markushi** [comment]
@smeubank how does this play together with client reports? Should dropped events/transactions be considered / which category?

**Comment by kahest** [comment]
> @smeubank how does this play together with client reports? Should dropped events/transactions be considered / which category?

We aligned on this:
- yes, we report events that have been ignored using this API
- yes, we will introduce a new category (e.g. `ignored`) - requires update to the docs: https://develop.sentry.dev/sdk/client-reports/#envelope-item-payload
