### ISSUE TITLE
Use `/envelope` endpoint when Performance Monitoring is enabled 

### ISSUE THREAD

**Issue by HazAT** [getsentry/team-webplatform-meta#49]
AND attach DSC to envelope header to all outgoing events

Relay PR: https://github.com/getsentry/relay/pull/1983

```[tasklist]
### Tasks
- [x] Javascript: https://github.com/getsentry/sentry-javascript/issues/7819
- [x] Node: https://github.com/getsentry/sentry-javascript/issues/7819
- [x] Python: https://github.com/getsentry/sentry-python/pull/2009
- [x] PHP https://github.com/getsentry/sentry-php/pull/1518
- [x] Java
- [x] .NET
- [x] Ruby
- [x] Go
```

Fixes: https://github.com/getsentry/team-webplatform-meta/issues/45

**Comment by adinauer** [comment]
Found no trace of using `/store` endpoint in Java SDK, only `/envelope`. DSC is attached to envelope headers for transactions and errors.

**Comment by bruno-garcia** [comment]
`/store` was dropped on cocoa/android/java/dotnet/dart in 2021 or earlier
