### ISSUE TITLE
Remove relay from all layers

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/team-webplatform-meta#58]
- [x] remove relay from python layer - https://github.com/getsentry/sentry-python/pull/2068
- [x] remove relay from js layer - https://github.com/getsentry/sentry-javascript/pull/8080
- [x] remove github action
- [ ] ~remove rust extension~ will be revisited after some time
