### ISSUE TITLE
[EPIC] Improve automatic- and manual instrumentation DX for tracing

### ISSUE THREAD

**Issue by danielkhan** [getsentry/team-webplatform-meta#72]
# Problems
* Our manual instrumentation on the backend lacks technology currency -> we don't support all well-known libraries and frameworks.
* Our user-facing SDK API is complicated to use because it leaks internal concepts like hubs, scopes, and transactions (as a means to combine and batch spans).

# User Stories
* As a developer, I want Sentry to automatically instrument all core APIs of a platform and a wide array of third-party libraries like databases, queues, and frameworks so that my traces are comprehensive and complete.
* As a developer, I want the SDK to offer an easy-to-use API to manually instrument code paths and propagate context where manual instrumentation is impossible, to avoid observability gaps.
* As a developer, I don't want to choose between two tracing implementations (Sentry, vs. OpenTelemetry).
* As a developer, I want Sentry to provide me with the best developer experience (DX) possible and provide a curated solution even if OpenTelemetry is used in the background.
* As Sentry, we don't want to degrade existing capabilities or rely on OpenTelemetry to fix bugs.
* As Sentry, we want to make this switch without requiring changes to downstream services.

# Clarifications
* The decision to use OpenTelemetry to power our framework instrumentation was already made
* While the API should be consistent on frontend and backend, we will still stick to Sentry on the frontend as OTel Mobile and Browser are still behind.
* The goal of this initiative is *not* to create an OTLP span ingest endpoint or to support OpenTelemetry to claim support (we support OTel already today).
* We chose this direction because OTel provides excellent tech coverage and a well-defined well-known nomenclature and API for adding manual instrumentation (Traces, Spans, Tags, etc.).
* We want to curate how we distribute OpenTelemetry to our users. This means they will still install the Sentry SDK, not vanilla OTel.
* Sentry has features Otel does not have, so our API will likely be a superset of the OTel API, and that is ok as long as we make sure that we can still stay up-to-date with the OTel project.
* When designing the API, please refer to the [OpenTelemetry Tracing Spec](https://opentelemetry.io/docs/specs/otel/trace/api/). 
* We want to minimize dependencies to other Sentry initiatives to avoid deadlocks - as such, the goal is to transform the emitted data to the Sentry schema as much as possible. There should be no changes on the backend required but we can seek out synergies when changes are due anyways.
* Eventually and one day we may natively support OTel schema and OTLP on ingest.

# Definition of done
- [ ] Our SDK come with the same tech currency as OpenTelemetry
- [ ] We provide an easy-to-use, largely OTel-compatible tracing SDK for manual instrumentation.
- [ ] We can stay up-to-date with OTel and have tests in place to protect us from regressions because of API changes.
- [ ] Older SDKs still work with our backend as before.

# Tasks
- [x] https://github.com/getsentry/team-webplatform-meta/issues/89
- [ ] https://github.com/getsentry/rfcs/pull/101

<details>
<summary>FAQ</summary>

### Why do we want users not longer have to think about transactions/hubs/scopes?

Because they are an implementation detail of Sentry's SDK. Transactions on one had are a bit more front and center but for a user to achieve a simple measurement (Span) we shouldn't require them to understand all these concepts. We internally need to abstract away this complexity and let the user measure what they want simple as e.g.: `startSpan`/`finishSpan` and/or `trace` callback function.

### Why OTEL - or - How we want to use OTEL?

Today the OTEL setup is unnecessarily complex and it feels like either you have to use Sentry or use OTEL - The end result has to be that there is only one way and to achieve the highest possible instrumentation we have to use OTEL underneath to cover all integrations possible.

### How do we make sure that the user always gets a measurement?

At any point in time - we want to ensure whenever the user measures something - it ends up in Sentry. Specific example even if today there is no ongoing transaction we create one under the hood and send it to Sentry.

</details>

**Comment by smeubank** [comment]
https://github.com/getsentry/rfcs/pull/101

**Comment by stephanie-anderson** [comment]
Closing in favor of splitting the work in smaller projects. Content of this issue has been adopted. Please, find the new project issues here:
- https://github.com/getsentry/team-sdks/issues/3
- https://github.com/getsentry/team-sdks/issues/4
