### ISSUE TITLE
Unify Bug Report Templates

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/team-webplatform-meta#82]
I noticed all our issue templates for bug reports differ and ask for very different information and levels of details. I will go through all and try to bring the best of all to each of them.

After comparing all web SDK bug report templates, I suggest to:
- always use forms for creating issues (instead of markdown)
- always set the label "Type: Bug" for bug reports
- always ask users where they host (SaaS / on-prem)
- always be specific about the "SDK version" (let's not call it environment etc)
- let users know what to expect after creating an issue (see Java, where we link to the triage process)

See Miro for more details: https://miro.com/app/board/uXjVMBwtrF8=/
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-php/pull/1565
- [ ] https://github.com/getsentry/sentry-laravel/pull/728
- [ ] https://github.com/getsentry/sentry-symfony/pull/744
```
